import type { Metadata } from "next";
import { Barlow } from 'next/font/google'
import "./globals.css";

const barlow = Barlow({
  weight: ["900", "500", "700"],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
